### ISSUE TITLE
various dlls missing from release/newest

### ISSUE THREAD

**Issue by goofyseeker311** [swfans/swars#74]
mingw32 related dlls missing, when using gog version of syndicate wars and just extracting the zip contents to suitable locations.

download what installer?

**Comment by mefistotelis** [comment]
The installer is currently outdated - noone is adjusting it to the changes in the project.

In case anyone would like to update it, here it is:
https://github.com/swfans/swars/blob/master/res/swars-setup.nsi

For missing DLLs - which exactly?
We use `objdump` to find any DLLs used by the binary and include them in build artifacts:
https://github.com/swfans/swars/blob/master/src/Makefile.am#L169

**Comment by goofyseeker311** [comment]
well: issue 1, not using cd but the gog installer.
thing 2: currently compiling the whole package from scratch, trying to circumvent the cd stuff

**Comment by goofyseeker311** [comment]
it works after extracting the install package files by hand, into the gog installed game files swars folder.

**Comment by mefistotelis** [comment]
For latest version, go to "Actions" tab and download ZIP from there.
Make sure to copy 'conf' folder, and replace files in `qdata` with content of `lang/eng` folder.

For figuring out issues, check `error.log` generated after you run the game.

**Comment by goofyseeker311** [comment]
> For latest version, go to "Actions" tab and download ZIP from there. Make sure to copy 'conf' folder, and replace files in `qdata` with content of `lang/eng` folder.
> 
> For figuring out issues, check `error.log` generated after you run the game.

specifically that actions package does not include all required dlls.

**Comment by mefistotelis** [comment]
> specifically that actions package does not include all required dll

Yep, you're right. Thanks.

> so why are not the contents of the actions package to auto-replace the contents in the proper folder when unpacking?

User may want a different language than english.

**Comment by goofyseeker311** [comment]
> User may want a different language than english.

default unpack should be english, other languages should be extra work.

**Comment by mefistotelis** [comment]
> default unpack should be english, other languages should be extra work.

The SW CD also has the `eng` folder and you have to copy from it. Or use a script which does that for you.
So not sure if it would help to have different rules for port files.

**Comment by goofyseeker311** [comment]
> > default unpack should be english, other languages should be extra work.
> 
> The SW CD also has the `eng` folder and you have to copy from it. Or use a script which does that for you. So not sure if it would help to have different rules for port files.

even after overwriting the qdata files, the latest actions version shows bugged map and mission will not start. older 797 version works. I dont have the cd, only the gog default data files from normal install.

**Comment by goofyseeker311** [comment]
errors are as follows:

bflibrary ver 0.1.2.0 (standard release)
LOG CREATED  @ 18:24:54  16-09-2023

Error: Bflib: LbFileOpen: file does not exist: "data/tex06.dat"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/default.ini"
Error: Bflib: LbFileOpen: file does not exist: "qdata/keys.dat"
Error: Bflib: LbFileOpen: file does not exist: "data\peepdefs.dat"
Error: Bflib: LbFileOpen: file does not exist: "conf\miss004.ini"
Error: Bflib: LbFileOpen: file does not exist: "conf\cities.ini"
Error: SWars: read_cities_conf_file: Could not open 'conf\cities.ini' file, cities list empty.
Warning: SWars: read_cities_conf_file: conf\cities.ini(line 1): Could not find "[common]" section, file skipped.
Error: Bflib: LbFileOpen: file does not exist: "conf\cities.ini"
Error: SWars: read_cities_conf_file: Could not open 'conf\cities.ini' file, cities list empty.
Warning: SWars: read_cities_conf_file: conf\cities.ini(line 1): Could not find "[common]" section, file skipped.
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Warning: Bflib: LbScreenReset: screen got reset while locked


[error.log](https://github.com/swfans/swars/files/12641014/error.log)

**Comment by mefistotelis** [comment]
These are the problem:

```
Error: Bflib: LbFileOpen: file does not exist: "conf\miss004.ini"
Error: Bflib: LbFileOpen: file does not exist: "conf\cities.ini"
```

**Comment by goofyseeker311** [comment]
idk if there is "select all" button, but moving stuff one-by-one is very annoying. should work more like cannon fodder, all in squads or at once.

**Comment by mefistotelis** [comment]
> idk if there is "select all" button

Like in original game, you have interface items on the left to select all.

**Comment by goofyseeker311** [comment]
> > idk if there is "select all" button
> 
> Like in original game, you have interface items on the left to select all.

yep found it, very confusingly implemented (originally). do you plan to increase resolution of the source port?

**Comment by mefistotelis** [comment]
You can already do it, in source - there is a variable storing video mode.
And for any resolution - there's a function to register new modes.

It's just not bound together and exported to conf file.

**Comment by goofyseeker311** [comment]
errors in the older version (swars-0_3_3_797-win32-patch.zip):

bflibrary ver 0.1.2.0 (standard release)
LOG CREATED  @ 18:32:30  16-09-2023

Error: Bflib: LbFileOpen: file does not exist: "data/tex06.dat"
Error: Bflib: LbMemoryAllocLow: failed memory allocation of 256 bytes
Error: Bflib: LbDataLoadAll: *VESA: cannot allocate memory
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/.ini"
Error: Bflib: LbFileOpen: file does not exist: "qdata/keys.dat"
Error: Bflib: LbFileOpen: file does not exist: "data\peepdefs.dat"
Error: Bflib: LbFileOpen: file does not exist: "qdata/keys.dat"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Error: SWars: ogg_vorbis_stream_open: .\music\track_2.ogg: Cannot fopen: No such file or directory
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Warning: Bflib: LbScreenReset: screen got reset while locked

[error797.log](https://github.com/swfans/swars/files/12641041/error797.log)

**Comment by goofyseeker311** [comment]
> You can already do it, in source - there is a variable storing video mode. And for any resolution - there's a function to register new modes.
> 
> It's just not bound together and exported to conf file.

why not, say 1080p or more should be the default. just was wondering that its not selectable in the depth settings menu.

**Comment by mefistotelis** [comment]
> why not a conf file or game config?

I don't meed it. I don't use it. I don't care.

There is an Issue created for that, I think.

**Comment by goofyseeker311** [comment]
> > why not a conf file or game config?
> 
> I don't meed it. I don't use it. I don't care.
> 
> There is an Issue created for that, I think.

why would you assume an user would have dev environment setup to change things?

**Comment by goofyseeker311** [comment]
btw 2bd8621 still is not a full self-contained package, missing the dlls and other support files.

**Comment by mefistotelis** [comment]
> why would you assume an user would have dev environment setup to change things?

I don't ask users to change this. Told you, as you've mentioned you're already setting up dev env.

> when the toolchain with all the moving parts especially cpython takes a ton of time to setup. installing visual studio etc?

I don't use VS. I use Python from mingw32, so my setup was like `pacman -S mingw32-python` (writing from memory, but proper cmd is in readme).

**Comment by goofyseeker311** [comment]
> > why would you assume an user would have dev environment setup to change things?
> 
> I don't ask users to change this. Told you, as you've mentioned you're already setting up dev env.
> 
> > when the toolchain with all the moving parts especially cpython takes a ton of time to setup. installing visual studio etc?
> 
> I don't use VS. I use Python from mingw32, so my setup was like `pacman -S mingw32-python` (writing from memory, but proper cmd is in readme).

right, both ways better. no dev and dev versions.
I dont have knowledge how to set up mingw32 python.
if those were also in the setup list, it would be simpler to have the dev env up.

**Comment by mefistotelis** [comment]
> if those were also in the setup list

https://github.com/swfans/swars#build-example---msys2-updated-2022-01-on-windows

**Comment by goofyseeker311** [comment]
> > if those were also in the setup list
> 
> https://github.com/swfans/swars#build-example---msys2-updated-2022-01-on-windows

nope, also missing python stuff and autotools etc.

**Comment by goofyseeker311** [comment]
> I don't ask users to change this. Told you, as you've mentioned you're already setting up dev env.

wouldnt it be suitable if the source port had the higher resolutions (selection) as a default feature? assuming it would be nice.

**Comment by goofyseeker311** [comment]
when the 3-line all units move is turned on, they will not fire.

**Comment by mefistotelis** [comment]
> wouldnt it be suitable if the source port had the higher resolutions (selection) as a default feature?

I already mentioned there's an "Issue" for that. You may comment there, if you'd like such feature.
#14

**Comment by goofyseeker311** [comment]
> > wouldnt it be suitable if the source port had the higher resolutions (selection) as a default feature?
> 
> I already mentioned there's an "Issue" for that. You may comment there, if you'd like such feature. #14

well you already said there is such a feature in the source already.

**Comment by Moburma** [comment]
> when the 3-line all units move is turned on, they will not fire.

You need to select weapons for all units. Right click on the weapons bar to do this. Read the manual before playing.

> well you already said there is such a feature in the source already.

There are odd graphics glitches exposed at high resolutions due to the engine not being designed to work at such resolutions. As such it really needs someone prepared to get stuck in deep into the engine code to release it as a proper end user feature. If no one is prepared to do that then to be honest it makes sense not to expose this to end users as they WILL just report all the known problems and get upset.

**Comment by goofyseeker311** [comment]
> > when the 3-line all units move is turned on, they will not fire.
> 
> You need to select weapons for all units. Right click on the weapons bar to do this. Read the manual before playing.

no, all weapons (uzis) are selected, group move is selected, and they will just stand there being shot.


> > well you already said there is such a feature in the source already.
> 
> There are odd graphics glitches exposed at high resolutions due to the engine not being designed to work at such resolutions. As such it really needs someone prepared to get stuck in deep into the engine code to release it as a proper end user feature. If no one is prepared to do that then to be honest it makes sense not to expose this to end users as they WILL just report all the known problems and get upset.

ok glitch then. maybe later.

**Comment by Moburma** [comment]
> clarification: player activated firing by right-clicking works at target. automatic firing at enemies is disabled when the 3-lines icon on the left is active. I dont know if its intended to disable automatic firing when in group move mode. feels a bit nonsense to do so.
> 
> also if the game was designed this way, then bad on bullfrog design.

This is the point of the "mood" bar which controls such behaviour, as explained in the manual.

**Comment by goofyseeker311** [comment]
> > clarification: player activated firing by right-clicking works at target. automatic firing at enemies is disabled when the 3-lines icon on the left is active. I dont know if its intended to disable automatic firing when in group move mode. feels a bit nonsense to do so.
> > also if the game was designed this way, then bad on bullfrog design.
> 
> This is the point of the "mood" bar which controls such behaviour, as explained in the manual.

ok I blame the game design then, very annoying to move fast and efficiently while also firing. not on you, not on me.

**Comment by goofyseeker311** [comment]
anyways, current errors (swars-0_3_3_1354-win32-patch):

bflibrary ver 0.1.2.0 (standard release)
LOG CREATED  @ 19:01:33  16-09-2023

Error: Bflib: LbFileOpen: file does not exist: "data/tex06.dat"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/default.ini"
Error: Bflib: LbFileOpen: file does not exist: "qdata/keys.dat"
Error: Bflib: LbFileOpen: file does not exist: "data\peepdefs.dat"
Error: Bflib: LbFileOpen: file does not exist: "conf\miss004.ini"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars1.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars2.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars3.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars4.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars5.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars6.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwars7.sav"
Error: Bflib: LbFileOpen: file does not exist: "qdata/savegame/synwarsm.sav"
Error: Bflib: LbFileOpen: file does not exist: "maps/map035.b&b"
Warning: SWars: load_level_pc: Local player group equal 0 will cause issues; fix the level
Error: Bflib: LbFileOpen: file does not exist: "maps/map035.b&b"
Warning: SWars: load_level_pc: Local player group equal 0 will cause issues; fix the level
Warning: Bflib: LbScreenReset: screen got reset while locked

[error1354.log](https://github.com/swfans/swars/files/12641214/error1354.log)

**Comment by goofyseeker311** [comment]
also some unknown error when compiling cdparanoia (pwd.h does not exist, even if configure finishes successfully)

**Comment by mefistotelis** [comment]
> also some 'polib' complains when trying to compile the main project file

Hm, yeah the info on polib dependency is probably missing from README, that's recent change.

`pip3 install polib` should fix that.

**Comment by goofyseeker311** [comment]
nope it did not fix it.

make[1]: Entering directory '/home/tapio/swars-master/release/lang'
/usr/bin/mkdir -p "eng"
/mingw32/bin/python ../../util/textwad.py -t "../../conf/char_encoding_tbl_eu.txt" -m "../../conf/char_encoding_tblm_eu.txt" -w eng/alltext.wad -c ../../lang/alltext_syndct_eng.pot ../../lang/alltext_church_eng.pot ../../lang/alltext_punks_eng.pot ../../lang/alltext_comm_eng.pot
Traceback (most recent call last):
  File "C:\msys64\home\tapio\swars-master\util\textwad.py", line 34, in <module>
    import polib
ModuleNotFoundError: No module named 'polib'
make[1]: *** [Makefile:705: eng/alltext.wad] Error 1
make[1]: Leaving directory '/home/tapio/swars-master/release/lang'
make: *** [Makefile:438: all-recursive] Error 1

**Comment by mefistotelis** [comment]
You have more than one Python and pip3 installed that on not the one you use?

**Comment by goofyseeker311** [comment]
> You have more than one Python and pip3 installed that on not the one you use?

idk. I ran pacman -S mingw-w64-i686-python3.

**Comment by mefistotelis** [comment]
Ok so you use msys2.

Then you're modifying PATH as explained in README.
Try:
```
which python3
PATH="/mingw32/bin:$PATH" which python3
```

And look whether they point to the same Python.

**Comment by goofyseeker311** [comment]
> Ok so you use msys2.
> 
> Then you're modifying PATH as explained in README. Try:
> 
> ```
> which python3
> PATH="/mingw32/bin:$PATH" which python3
> ```
> 
> And look whether they point to the same Python.

I just removed all pythons and reinstalled pip/python

**Comment by goofyseeker311** [comment]
nice acrobatics

**Comment by mefistotelis** [comment]
You can copy the files to the same folders they are in ZIPs:
```
PATH="/mingw32/bin:$PATH" make V=1 DESTDIR=$PWD/pkg install
```

**Comment by goofyseeker311** [comment]
yep self-compiled package seems to work out of the box now, proper dlls, tho I would put the qdata files by default in english so that they overwrite by default in the correct place

**Comment by mefistotelis** [comment]
> tho I would put the qdata files by default in english so that they overwrite by default in the correct place

I'm not yet ready for such change.

If there are any deviations from current instructions for the GOG version, you could describe them to improve that - either here, on in a PR.

**Comment by goofyseeker311** [comment]
ok. one more thing, somehow the program window, it is 640x480, but appears in windows to be as if its drawn to the desktop resolution, so OBS shows it as 640x480 top-left corner image, not full screen, even if window captured, and game capture does not even recognize that the game is running, even if its in the drop down menu.

some SDL display shenanigans.

**Comment by mefistotelis** [comment]
> some SDL display shenanigans.

If this can even be influenced, that would be by SDL config - you may try searching for that, there are SDL settings which can be changed via environment vars.

But I don't think there's a place to report this as a bug - the port does not include SDL modifications, and SDL project itself no longer does any development on SDL1.

**Comment by goofyseeker311** [comment]
I mean its not an SDL dev issue, but SDL usage issue, if any.

**Comment by mefistotelis** [comment]
> switch to SDL2?

Personally I'm not planning to work on it any time soon.
Though shouldn't be hard, as KeeperFX did that switch. And the bflibrary code there is very similar.

**Comment by Moburma** [comment]
I will have a go at updating the NSIS installer to include the new DLLs and conf files, and also will try and include a GOG version option.

**Comment by Moburma** [comment]
@goofyseeker311 Would you be interested in testing a new Windows installer? It supports the GOG version now. If you could give any feedback I'd be grateful, see this issue: https://github.com/swfans/swars/issues/79
